
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: family_blog_development

test:
  <<: *default
  database: family_blog_test

production:
  <<: *default
  database: family_blog_production
  username: family_blog
  password: <%= ENV['FAMILY_BLOG_DATABASE_PASSWORD'] %>
  url: <%= ENV['DATABASE_URL'] %>
